---
- name: Main Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for 10 seconds
      pause:
          seconds: 10
          #msg: "Wait is over"
            
- import_playbook: "playbooks/PingServers.yml"

- name: Run Smoketest before patch
  hosts: localhost
  gather_facts: no
  tasks:
  
- import_playbook: "playbooks/SmokeTest.yml"

- name: Patching servers
  hosts: localhost
  gather_facts: no
  tasks:
  
- import_playbook: "playbooks/UpdateFedora.yml"

- name: Run Smoketest after patch
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for 10 seconds
      pause:
        seconds: 10

- import_playbook: "playbooks/SmokeTest.yml"
