---
- name: Main Playbook
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Wait for 10 seconds
      pause:
          seconds: 10
          #msg: "Wait is over"
            
- import_playbook: "playbooks/PingServers.yml"

- name: Run Smoketest before patch
  hosts: localhost
  gather_facts: no
  tasks:
  
- import_playbook: "playbooks/SmokeTest.yml"

 #   - name: Import UpdateFedora playbook
 #     import_playbook: "playbooks/UpdateFedora.yml"

#    - name: Wait for 30 seconds
 #     pause:
  #      seconds: 30

   # - name: Import SmokeTest playbook again
 #     import_playbook: "playbooks/SmokeTest.yml"
