---
- name: Run PingServers
  tasks:
    - import.playbook: PingServers.yml

- name: Run SmokeTest
  tasks:
    - import.playbook: SmokeTest.yml

- name: Run UpdateFedora
  tasks:
    - import.playbook: UpdateFedora.yml
    
- name: Run SmokeTest after
  tasks:
    - import.playbook: SmokeTest.yml
