---
tasks:
    - ansible.builtin.debug:
        msg: play1
        
- name: Run PingServers
    - ansible.builtin.import_playbook: PingServers.yml

- name: Run SmokeTest
    - ansible.builtin.import_playbook: SmokeTest.yml

- name: Run UpdateFedora
    - ansible.builtin.import_playbook: UpdateFedora.yml
    
- name: Run SmokeTest after
    - ansible.builtin.import_playbook: SmokeTest.yml
